"""create bot info

Revision ID: f7244f98d152
Revises: 
Create Date: 2024-02-06 22:32:58.102927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7244f98d152'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('min_order', sa.Double(), nullable=True),
    sa.Column('price_per_1000', sa.Double(), nullable=True),
    sa.Column('price_for_all_users', sa.Double(), nullable=True),
    sa.Column('cost_mailing', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_info'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_info')
    # ### end Alembic commands ###
